secret_key: "RANDOM-STRING"  # Random keys
nobroadcast: True            # Safety mode

mail_host: "SERVER:589"
mail_user: "user"
mail_pass: "password"
mail_from: "noreply@faucet.org"

admins:
 - adminA@example.com
 - adminB@example.com

minIPAge: 300  # How long in secs does an IP need to wait to register a new account?
witness_url: "wss://node.testnet.bitshares.eu"

registrar: "faucet"
default_referrer: "xeroc"
referrer_percent: 50  # in percent
wif: "5KAniAqT1y4orQQ7KopKJ85QQXbVU92jbpV6KGGy5b396LpLYLM"

balance_mailthreshold: 500  # if balances goes below this, you will be notified

core_asset: "TEST"
donation_amount: 10000
donation_asset: TEST
